### PR TITLE
Added a way to find open port for holochainAppPort & holochainAdminPort

### PR DESCRIPTION
**Pull request by fayeed**

### CODE REVIEW

**Comment by fayeed** [comment]
Currently, we are only storing the `holochainAdminPor`t port in the config so it's persistent but `holochainAppPort` is not and can have a different port if the default one is not found, should this also be persisted in the config?

**Review by lucksus — APPROVED** [review]
This looks good. I don't think we need to persist `hcPortAdmin` since, as you say, it is already persisted in the conductor config - and that is normative.

**Comment by fayeed** [comment]
@lucksus I mean `holochainAppPort` is not saved in the config.

**Comment by jdeepee** [comment]
@lucksus still good to merge?

**Pull request merged**
